import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modalContainer: {
    backgroundColor: '#22272B',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#384148',
    width: '100%',
    maxWidth: 650,
    height: '85%',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#384148',
    backgroundColor: '#1D2125',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  title: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#B6C2CF',
  },
  topActions: {
    paddingHorizontal: 14,
    paddingTop: 12,
    gap: 8,
  },
  hintText: {
    fontSize: 12,
    color: '#8C9BAB',
    fontWeight: '600',
    textAlign: 'center',
  },
  gpsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2C333A',
    borderWidth: 1,
    borderColor: '#384148',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
  },
  gpsBtnText: {
    color: '#B6C2CF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  inputsRow: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  label: {
    fontSize: 12,
    fontWeight: '600',
    color: '#8C9BAB',
    marginBottom: 4,
  },
  inputWithButtons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  input: {
    flex: 1,
    backgroundColor: '#1D2125',
    borderWidth: 1,
    borderColor: '#384148',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: '#FFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  nudgeBtnGroup: {
    flexDirection: 'column',
    marginLeft: 4,
    gap: 2,
  },
  nudgeBtn: {
    backgroundColor: '#384148',
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapFrame: {
    flex: 1,
    backgroundColor: '#1D2125',
    marginHorizontal: 14,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#384148',
  },
  footer: {
    padding: 14,
    backgroundColor: '#1D2125',
    borderTopWidth: 1,
    borderTopColor: '#384148',
    gap: 8,
  },
  confirmBtn: {
    backgroundColor: '#2C333A',
    borderWidth: 1,
    borderColor: '#384148',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  confirmBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 15,
  },
  cancelBtn: {
    backgroundColor: '#1D2125',
    borderWidth: 1,
    borderColor: '#384148',
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
  },
  cancelBtnText: {
    color: '#8C9BAB',
    fontWeight: '600',
    fontSize: 14,
  },
});
