export const OPCIONES_TIPO_ACCION_COBRANZA = [
  'ACCIÓN EFECTIVA',
  'ACCIÓN NEGATIVA',
];

export const OPCIONES_TIPO_CONTACTO_COBRANZA = [
  'LLAMADA TELEFONICA',
  'MENSAJE WHATSAPP',
  'MENSAJE TEXTO',
  'CORREO',
  'VISITA RESIDENCIAL',
];

// --- ACCIÓN EFECTIVA (7 opciones) ---
export const RESULTADOS_EFECTIVOS = [
  'COBRO EFECTIVO',
  'CONVENIO DE PAGO',
  'ABONO PARCIALMENTE',
  'RECUPERADO',
  'NO CONTESTO',
  'LUEGO PASA POR OFIC',
  'PIDE AJUSTE DE PLAN',
];

// --- ACCIÓN NEGATIVA (10 opciones) ---
export const RESULTADOS_NEGATIVOS = [
  'FUERA DE ZONA',
  'PIDE RETIRO',
  'RECHAZO A PAGAR POR DIAS SIN SERVICIO',
  'TIENE FALLA',
  'INCONFORMIDAD CON MONTO',
  'NO RECONOCE DEUDA',
  'REHUSA ENTREGAR EQUIPO',
  'PUERTO LIBERADO',
  'TIENE OTRO SERVICIO',
  'NO DESEA PAGAR',
];

// Opciones de resultado de cobranza combinadas
export const OPCIONES_RESULTADO_COBRANZA = [
  ...RESULTADOS_EFECTIVOS,
  ...RESULTADOS_NEGATIVOS,
];

