import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  cardSection: {
    backgroundColor: '#1D2125',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#384148',
    marginTop: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#384148',
    paddingBottom: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#B6C2CF',
  },
  formContainer: {
    gap: 4,
  },
  whatsappCard: {
    backgroundColor: '#22272B',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#384148',
    marginBottom: 14,
    gap: 10,
  },
  whatsappInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  whatsappLabel: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#8C9BAB',
    letterSpacing: 0.5,
  },
  whatsappNombre: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 2,
  },
  whatsappMeta: {
    fontSize: 12,
    color: '#8C9BAB',
    marginTop: 2,
  },
  btnWhatsApp: {
    backgroundColor: '#1D2125',
    borderWidth: 1,
    borderColor: '#384148',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
    gap: 8,
  },
  btnWhatsAppText: {
    color: '#B6C2CF',
    fontWeight: 'bold',
    fontSize: 13,
  },
  btnGuardar: {
    backgroundColor: '#A0B2C6',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 14,
    borderRadius: 8,
    gap: 8,
    marginTop: 12,
  },
  btnDisabled: {
    opacity: 0.5,
  },
  btnGuardarText: {
    color: '#1D2125',
    fontWeight: 'bold',
    fontSize: 15,
  },
  historialContainer: {
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#384148',
  },
  historialTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#8C9BAB',
  },
  historialItem: {
    backgroundColor: '#2C333A',
    padding: 10,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#384148',
  },
  historialFecha: {
    fontSize: 11,
    color: '#8C9BAB',
    marginBottom: 4,
  },
  historialTxt: {
    fontSize: 12,
    color: '#B6C2CF',
  },
  historialAccionBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#384148',
  },
});
