import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#1E232A',
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: '#384148',
  },
  description: {
    fontSize: 12,
    color: '#8C9BAB',
    marginBottom: 12,
    lineHeight: 18,
  },
  buttonsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  actionBtn: {
    flex: 1,
    backgroundColor: '#2C333A',
    borderWidth: 1,
    borderColor: '#384148',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  actionBtnActive: {
    backgroundColor: '#384148',
  },
  actionBtnText: {
    color: '#B6C2CF',
    fontWeight: 'bold',
    fontSize: 13,
    textAlign: 'center',
  },
  formCard: {
    backgroundColor: '#151921',
    borderRadius: 8,
    padding: 14,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#384148',
  },
  formTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#B6C2CF',
    marginBottom: 12,
  },
  fieldLabel: {
    fontSize: 11,
    color: '#8C9BAB',
    marginBottom: 4,
    fontWeight: 'bold',
  },
  textInput: {
    backgroundColor: '#22272B',
    color: '#FFFFFF',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 13,
    borderWidth: 1,
    borderColor: '#384148',
    marginBottom: 10,
  },
  readOnlyField: {
    backgroundColor: '#1E232A',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#2C333A',
    marginBottom: 10,
  },
  readOnlyText: {
    color: '#8C9BAB',
    fontSize: 13,
  },
  uploadBtn: {
    backgroundColor: '#22272B',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#384148',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 14,
  },
  uploadBtnAttached: {
    borderColor: '#A0B2C6',
  },
  uploadBtnText: {
    color: '#B6C2CF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  submitBtn: {
    backgroundColor: '#A0B2C6',
    borderRadius: 6,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  submitBtnText: {
    color: '#1D2125',
    fontWeight: '900',
    fontSize: 13,
    textTransform: 'uppercase',
  },
  btnDisabled: {
    opacity: 0.6,
  },
});
