import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  cardAsignado: {
    backgroundColor: '#1E232A',
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: '#384148',
  },
  headerAsignado: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  badgeAsignado: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
  },
  badgeText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#3B82F6',
    letterSpacing: 0.5,
  },
  fechaTexto: {
    fontSize: 11,
    color: '#8C9BAB',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  avatarCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#2C333A',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#384148',
  },
  nombreAsesor: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#F4F5F7',
  },
  subtextoAsesor: {
    fontSize: 11,
    color: '#8C9BAB',
    marginTop: 2,
  },
  botonesContainer: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  botonConcretar: {
    flex: 2,
    backgroundColor: '#22A06B',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textoBotonConcretar: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 13,
  },
  botonReasignar: {
    flex: 1,
    backgroundColor: '#1D2125',
    borderWidth: 1,
    borderColor: '#384148',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textoBotonReasignar: {
    color: '#8C9BAB',
    fontWeight: '600',
    fontSize: 12,
  },
  contenedorSelector: {
    backgroundColor: '#1E232A',
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: '#384148',
  },
  instruccionTexto: {
    fontSize: 12,
    color: '#B6C2CF',
    marginBottom: 10,
    lineHeight: 16,
  },
  advertenciaSinFiltro: {
    fontSize: 11,
    color: '#ECC94B',
    marginBottom: 8,
    fontStyle: 'italic',
  },
  itemAsesor: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#1D2125',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#384148',
    marginBottom: 8,
  },
  itemAsesorActual: {
    borderColor: '#579DFF',
    backgroundColor: '#1F2937',
  },
  itemAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#2C333A',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  itemNombre: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#B6C2CF',
  },
  itemRol: {
    fontSize: 10,
    color: '#8C9BAB',
    marginTop: 2,
    textTransform: 'uppercase',
  },
  botonSeleccionar: {
    backgroundColor: '#0C66E4',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
  },
  botonSeleccionarActual: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#579DFF',
  },
  textoSeleccionar: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 11,
  },
  botonCancelarReasignacion: {
    paddingVertical: 10,
    alignItems: 'center',
    marginTop: 4,
  },
  textoCancelar: {
    color: '#8C9BAB',
    fontSize: 12,
    fontWeight: '600',
  },
});
