import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  modalContainer: {
    maxHeight: '82%',
    backgroundColor: '#22272B',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#384148',
    overflow: 'hidden',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#384148',
    backgroundColor: '#1D2125',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#B6C2CF',
    letterSpacing: 0.5,
  },
  headerBadge: {
    backgroundColor: '#2C333A',
    borderWidth: 1,
    borderColor: '#384148',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  headerBadgeText: {
    color: '#B6C2CF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  closeBtn: {
    padding: 4,
  },
  filterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#2C333A',
    backgroundColor: '#22272B',
    gap: 8,
  },
  filterDropdownWrapper: {
    flex: 1,
    maxWidth: 160,
  },
  actionBtnsGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  actionPillBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#1D2125',
    borderWidth: 1,
    borderColor: '#384148',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 4,
  },
  actionPillText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#B6C2CF',
  },
  actionPillTextMuted: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#8C9BAB',
  },
  listContainer: {
    paddingHorizontal: 12,
    paddingTop: 8,
  },
  listContent: {
    paddingBottom: 16,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    gap: 12,
  },
  emptyText: {
    color: '#8C9BAB',
    fontSize: 13,
    textAlign: 'center',
  },
  itemCard: {
    borderRadius: 6,
    borderWidth: 1,
    padding: 10,
    marginBottom: 8,
    gap: 6,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemTypeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  itemBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: '#2C333A',
    borderWidth: 1,
    borderColor: '#384148',
  },
  itemBadgeText: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#8C9BAB',
  },
  unreadIndicatorDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#B6C2CF',
  },
  itemDate: {
    fontSize: 11,
    color: '#8C9BAB',
  },
  itemTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 2,
  },
  itemMessage: {
    fontSize: 12,
    color: '#B6C2CF',
    lineHeight: 17,
  },
  itemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 2,
  },
  miniBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 2,
    paddingHorizontal: 4,
  },
  miniBtnText: {
    fontSize: 11,
    color: '#8C9BAB',
  },
  permissionBanner: {
    backgroundColor: '#1D2125',
    borderBottomWidth: 1,
    borderBottomColor: '#384148',
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  permissionTextContainer: {
    flex: 1,
  },
  permissionTitle: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#B6C2CF',
  },
  permissionSubtitle: {
    fontSize: 10,
    color: '#8C9BAB',
    marginTop: 2,
    lineHeight: 14,
  },
  permissionBtn: {
    backgroundColor: '#2C333A',
    borderWidth: 1,
    borderColor: '#384148',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 4,
  },
  permissionBtnText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
});
