import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modalCard: {
    backgroundColor: '#22272B',
    borderRadius: 12,
    width: '100%',
    maxHeight: '85%',
    borderWidth: 1,
    borderColor: '#384148',
    overflow: 'hidden',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#384148',
    backgroundColor: '#2C333A',
  },
  headerTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#B6C2CF',
  },
  btnClose: {
    padding: 4,
  },
  tabRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#384148',
    backgroundColor: '#1D2125',
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabBtnActive: {
    borderBottomColor: '#A0B2C6',
    backgroundColor: '#22272B',
  },
  tabTxt: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#8C9BAB',
  },
  tabTxtActive: {
    color: '#B6C2CF',
  },
  body: {
    padding: 16,
    maxHeight: 400,
  },
  loadingBox: {
    padding: 30,
    alignItems: 'center',
  },
  loadingTxt: {
    color: '#8C9BAB',
    marginTop: 8,
    fontSize: 12,
  },
  emptyBox: {
    padding: 30,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#B6C2CF',
    marginBottom: 4,
  },
  emptySub: {
    fontSize: 12,
    color: '#8C9BAB',
    textAlign: 'center',
  },
  list: {
    gap: 8,
  },
  solicitudCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#2C333A',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#384148',
    gap: 12,
  },
  sectorNombre: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 2,
  },
  sectorMeta: {
    fontSize: 11,
    color: '#8C9BAB',
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  btnAprobar: {
    backgroundColor: '#A0B2C6',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
  },
  btnAprobarTxt: {
    color: '#1D2125',
    fontWeight: 'bold',
    fontSize: 12,
  },
  btnRechazar: {
    backgroundColor: '#1D2125',
    padding: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#384148',
  },
  aprobadoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2C333A',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#384148',
    gap: 10,
  },
  aprobadoDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#A0B2C6',
  },
  aprobadoNombre: {
    fontSize: 13,
    color: '#B6C2CF',
    fontWeight: '600',
  },
  footer: {
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: '#384148',
    backgroundColor: '#2C333A',
    alignItems: 'flex-end',
  },
  btnCerrar: {
    backgroundColor: '#1D2125',
    borderWidth: 1,
    borderColor: '#384148',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
  },
  btnCerrarTxt: {
    color: '#B6C2CF',
    fontWeight: 'bold',
    fontSize: 13,
  },
});
