import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#1D2125' },
  innerContainer: { flex: 1, paddingHorizontal: 16, paddingTop: 16 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  headerTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  headerIcon: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#2C333A',
    borderWidth: 1,
    borderColor: '#384148',
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: { fontSize: 20, fontWeight: 'bold', color: '#FFFFFF' },
  subtitle: { fontSize: 13, color: '#8C9BAB', marginTop: 2 },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#22272B',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#384148',
    padding: 4,
    gap: 4,
  },
  tabItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 6,
  },
  tabItemActive: { backgroundColor: '#2C333A' },
  tabItemActiveDev: { backgroundColor: '#2C333A' },
  tabItemActiveHis: { backgroundColor: '#2C333A' },
  tabText: { fontSize: 13, color: '#8C9BAB', fontWeight: '600' },
  tabTextActive: { color: '#FFFFFF', fontWeight: 'bold' },
  tabTextActiveDev: { color: '#FFFFFF', fontWeight: 'bold' },
  tabTextActiveHis: { color: '#FFFFFF', fontWeight: 'bold' },
  centerLoading: { padding: 40, alignItems: 'center' },
  loadingTxt: { color: '#8C9BAB', marginTop: 12, fontSize: 14 },
  scrollContent: { paddingBottom: 40, paddingTop: 16 },
});
