ALTER TABLE tableros ADD COLUMN IF NOT EXISTS es_favorito BOOLEAN DEFAULT false;
ALTER TABLE tableros ADD COLUMN IF NOT EXISTS descripcion TEXT;
ALTER TABLE tableros ADD COLUMN IF NOT EXISTS opacidad_listas NUMERIC DEFAULT 0.85;
ALTER TABLE tarjetas ADD COLUMN IF NOT EXISTS estado_archivo BOOLEAN DEFAULT false;
