import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1D2125',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1D2125',
  },
  webContainer: {
    width: '100%',
    maxWidth: 1024,
    alignSelf: 'center',
  },
  greeting: {
    fontSize: 14,
    color: '#8C9BAB',
    fontWeight: '500',
  },
  companyName: {
    fontSize: 32,
    fontWeight: '900',
    color: '#B6C2CF',
    marginTop: 0,
  },
  scrollContent: {
    paddingTop: 24,
    paddingBottom: 40,
  },
  sucursalSection: {
    marginBottom: 32,
  },
  sucursalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    paddingHorizontal: 24,
    marginBottom: 8,
  },
  sucursalTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#B6C2CF',
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  sucursalLocation: {
    fontSize: 12,
    color: '#8C9BAB',
    fontStyle: 'italic',
  },
  boardGroupContainer: {
    backgroundColor: 'transparent',
  },
  cardDashedGroup: {
    width: '100%',
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#2C333A',
    borderWidth: 1,
    borderColor: '#384148',
  },
  dashedText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#B6C2CF',
  },
  emptyText: {
    paddingHorizontal: 24,
    fontSize: 16,
    color: '#8C9BAB',
    fontStyle: 'italic',
    marginBottom: 16,
  },
  emptyContainer: {
    padding: 32,
    marginHorizontal: 24,
    backgroundColor: '#22272B',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#384148',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#B6C2CF',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptySubtext: {
    fontSize: 14,
    color: '#8C9BAB',
    textAlign: 'center',
    lineHeight: 22,
    maxWidth: 400,
    marginBottom: 24,
  },
  btnCrearSucursalEmpresa: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2C333A',
    borderWidth: 1,
    borderColor: '#384148',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 12,
  },
  btnCrearSucursalEmpresaText: {
    color: '#B6C2CF',
    fontSize: 15,
    fontWeight: 'bold',
  },
  swappingBanner: {
    position: 'absolute',
    bottom: 24,
    left: 24,
    right: 24,
    backgroundColor: 'rgba(0,0,0,0.85)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderRadius: 16,
    zIndex: 100,
  },
  swappingBannerText: {
    flex: 1,
    marginLeft: 12,
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  headerRow: {
    marginBottom: 32,
    marginTop: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerInfo: {
    flex: 1,
    marginRight: 16,
  },
  logoImg: {
    borderRadius: 8,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#22272B',
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 44,
    marginBottom: 24,
    marginTop: 4,
    borderWidth: 1,
    borderColor: '#384148',
    marginHorizontal: 24,
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: 15,
    color: '#FFFFFF',
  },
});
