import { StyleSheet } from 'react-native';

export const gestionOnlineStyles = StyleSheet.create({
  tableCard: {
    backgroundColor: '#22272B',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#384148',
    padding: 16,
    marginBottom: 20,
  },
  tableTopHeaderRow: {
    marginBottom: 16,
  },
  filterControlsRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: 12,
  },
  tableHeaderTitleWrapper: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.05)',
    paddingTop: 12,
  },
  tableHeaderFlex: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    flexWrap: 'wrap',
  },
  tableTitle: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  togglePieButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#1D2125',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#384148',
  },
  togglePieButtonTxt: {
    color: '#10B981',
    fontSize: 11,
    fontWeight: 'bold',
  },
  chartSectionWrapper: {
    backgroundColor: '#1D2125',
    borderRadius: 8,
    padding: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#384148',
  },
  sectionSubtitleHeader: {
    color: '#B6C2CF',
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 8,
    textAlign: 'center',
  },
  matrixContainer: {
    minWidth: 640,
    borderWidth: 1,
    borderColor: '#384148',
    borderRadius: 6,
    overflow: 'hidden',
  },
  matrixHeaderRow: {
    flexDirection: 'row',
    backgroundColor: '#1D2125',
    borderBottomWidth: 1,
    borderBottomColor: '#384148',
  },
  matrixHeaderCell: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: '#384148',
  },
  matrixHourHeaderCell: {
    width: 100,
    flex: 0,
  },
  matrixHeaderTxt: {
    color: '#8C9BAB',
    fontSize: 9,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  matrixBodyRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  matrixBodyCell: {
    flex: 1,
    paddingVertical: 6,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: 'rgba(255, 255, 255, 0.05)',
  },
  matrixHourCell: {
    width: 100,
    flex: 0,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    paddingLeft: 8,
  },
  matrixHourTxt: {
    color: '#B6C2CF',
    fontSize: 10,
    fontWeight: '600',
  },
  matrixCountBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  matrixCountBadgeActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
  },
  matrixCountTxt: {
    color: '#6B7280',
    fontSize: 11,
    fontWeight: '600',
  },
  matrixCountTxtActive: {
    color: '#10B981',
    fontWeight: 'bold',
  },
  matrixTotalRow: {
    flexDirection: 'row',
    borderTopWidth: 2,
    borderTopColor: '#384148',
  },
  matrixTotalHourTxt: {
    color: '#B6C2CF',
    fontWeight: '900',
    fontSize: 10,
  },
  matrixTotalTxt: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '900',
  },
});
