import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'center', alignItems: 'center', padding: 16 },
  container: { width: '100%', maxWidth: 550, height: 520, backgroundColor: '#22272B', borderRadius: 16, borderWidth: 1, borderColor: '#384148', overflow: 'hidden' },
  containerDesktop: { height: 580 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14, backgroundColor: '#1D2125', borderBottomWidth: 1, borderBottomColor: '#384148' },
  headerTitleRow: { flexDirection: 'row', alignItems: 'center' },
  title: { fontSize: 16, fontWeight: 'bold', color: '#FFF' },
  subtitle: { fontSize: 12, color: '#8C9BAB' },
  closeBtn: { padding: 4 },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 32 },
  emptyTitle: { color: '#FFF', fontSize: 18, fontWeight: 'bold', marginTop: 12 },
  emptySub: { color: '#8C9BAB', fontSize: 14, textAlign: 'center', marginTop: 6, lineHeight: 20 },
  emptySubCenter: { color: '#8C9BAB', fontSize: 14, textAlign: 'center', marginVertical: 40 },
  sectionTitle: { color: '#B6C2CF', fontSize: 14, fontWeight: 'bold', marginBottom: 12 },
  convCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#1D2125', padding: 12, borderRadius: 10, borderWidth: 1, borderColor: '#384148', marginBottom: 8 },
  avatarCircle: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#0C66E4', justifyContent: 'center', alignItems: 'center' },
  convNombre: { color: '#FFF', fontWeight: 'bold', fontSize: 14 },
  convUltimo: { color: '#8C9BAB', fontSize: 12, marginTop: 2 },
  chatBody: { flex: 1, backgroundColor: '#22272B' },
  msgBubble: { maxWidth: '80%', padding: 10, borderRadius: 12, marginBottom: 6 },
  msgBubbleMio: { alignSelf: 'flex-end', backgroundColor: '#0C66E4', borderBottomRightRadius: 2 },
  msgBubbleOtro: { alignSelf: 'flex-start', backgroundColor: '#1D2125', borderWidth: 1, borderColor: '#384148', borderBottomLeftRadius: 2 },
  msgTextoMio: { color: '#FFF', fontSize: 14, lineHeight: 20 },
  msgTextoOtro: { color: '#B6C2CF', fontSize: 14, lineHeight: 20 },
  msgHora: { fontSize: 10, color: 'rgba(255,255,255,0.6)', alignSelf: 'flex-end', marginTop: 4 },
  msgImgThumb: { width: 180, height: 140, borderRadius: 8, marginTop: 2, marginBottom: 2 },
  inputFooter: { flexDirection: 'row', alignItems: 'center', padding: 12, backgroundColor: '#1D2125', borderTopWidth: 1, borderTopColor: '#384148', gap: 8 },
  textInput: { flex: 1, backgroundColor: '#22272B', borderWidth: 1, borderColor: '#384148', borderRadius: 20, paddingHorizontal: 16, paddingVertical: 8, color: '#FFF', maxHeight: 80, fontSize: 14 },
  btnIcon: { padding: 8, justifyContent: 'center', alignItems: 'center' },
  btnSend: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#0C66E4', justifyContent: 'center', alignItems: 'center' },
  fullImgOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.92)', justifyContent: 'center', alignItems: 'center' },
  closeFullImg: { position: 'absolute', top: 40, right: 20, zIndex: 10, padding: 8 },
  fullImg: { width: '90%', height: '80%' },
});
