import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  fieldContainer: {
    marginBottom: 16,
    width: '100%',
  },
  fieldContainerCompact: {
    marginBottom: 0,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#B6C2CF',
    marginBottom: 6,
  },
  labelCompact: {
    fontSize: 11,
    color: '#8C9BAB',
    marginBottom: 4,
  },
  required: {
    color: '#E53E3E',
  },
  input: {
    backgroundColor: '#1D2125',
    borderWidth: 1,
    borderColor: '#384148',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    color: '#B6C2CF',
  },
  inputReadOnly: {
    backgroundColor: '#171B21',
    color: '#8C9BAB',
  },
  inputMultiline: {
    minHeight: 70,
    textAlignVertical: 'top',
  },
  selectBtn: {
    backgroundColor: '#1D2125',
    borderWidth: 1,
    borderColor: '#384148',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  selectBtnCompact: {
    height: 34,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 6,
  },
  btnDisabled: {
    opacity: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modalContent: {
    backgroundColor: '#2C333A',
    borderRadius: 12,
    width: '85%',
    maxWidth: 340,
    maxHeight: '60%',
    paddingBottom: 8,
    borderWidth: 1,
    borderColor: '#384148',
    elevation: 5,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#384148',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#B6C2CF',
  },
  optionItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#384148',
  },
  optionText: {
    fontSize: 15,
    color: '#B6C2CF',
    textTransform: 'capitalize',
  },
  optionTextSelected: {
    fontWeight: 'bold',
    color: '#90CDF4',
  },
  inputDocumentoContainer: {
    backgroundColor: '#1D2125',
    borderWidth: 1,
    borderColor: '#384148',
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    height: 48,
    overflow: 'hidden',
  },
  prefijoBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    height: '100%',
    gap: 6,
    backgroundColor: '#22272B',
  },
  prefijoText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#B6C2CF',
  },
  prefijoDivider: {
    width: 1,
    height: '60%',
    backgroundColor: '#384148',
  },
  inputDocumentoText: {
    flex: 1,
    height: '100%',
    paddingHorizontal: 12,
    fontSize: 16,
    color: '#B6C2CF',
  },
});
