import { StyleSheet, Platform, TextStyle } from 'react-native';

export const styles = StyleSheet.create({
  modalContentSide: {
    width: Platform.OS === 'web' ? 340 : '85%',
    height: '100%',
    backgroundColor: '#22272B',
    borderLeftWidth: 1,
    borderLeftColor: '#384148',
  },
  sideHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#384148',
  },
  sideTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  quickActionsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  quickActionBtn: {
    flex: 1,
    backgroundColor: '#2C333A',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#384148',
  },
  quickActionText: {
    color: '#B6C2CF',
    marginTop: 8,
    fontSize: 12,
    fontWeight: 'bold',
  },
  menuSection: {
    marginBottom: 24,
    borderTopWidth: 1,
    borderTopColor: '#384148',
    paddingTop: 16,
  },
  sectionSubtitle: {
    color: '#8C9BAB',
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 12,
    textTransform: 'uppercase',
  },
  membersRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  memberAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#0C66E4',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#22272B',
    overflow: 'hidden',
  },
  memberAvatarImg: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
  },
  memberAvatarText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  memberAvatarAdd: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#2C333A',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  menuListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
  },
  menuListItemDanger: {
    backgroundColor: 'rgba(246, 173, 85, 0.07)',
    borderRadius: 8,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: 'rgba(246, 173, 85, 0.25)',
    marginTop: 4,
  },
  menuListText: {
    color: '#B6C2CF',
    fontSize: 14,
    marginLeft: 12,
  },
  menuListTextDanger: {
    color: '#F6AD55',
    fontSize: 14,
    fontWeight: 'bold',
  },
  menuListSubtext: {
    color: '#8C9BAB',
    fontSize: 11,
    marginTop: 2,
  },
  descEditor: {
    backgroundColor: '#2C333A',
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
  },
  descInput: {
    color: '#FFFFFF',
    fontSize: 14,
    minHeight: 80,
    outlineStyle: 'none',
  } as unknown as TextStyle,
  descSaveBtn: {
    backgroundColor: '#0C66E4',
    borderRadius: 4,
    paddingVertical: 8,
    alignItems: 'center',
    marginTop: 12,
  },
  descSaveBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  memberModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  memberModalCard: {
    width: '100%',
    maxWidth: 320,
    backgroundColor: '#2C333A',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#384148',
    padding: 24,
    alignItems: 'center',
    elevation: 8,
  },
  memberModalCloseBtn: {
    position: 'absolute',
    top: 12,
    right: 12,
    padding: 6,
  },
  memberModalAvatarBox: {
    width: 80,
    height: 80,
    borderRadius: 40,
    marginBottom: 16,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#0C66E4',
  },
  memberModalAvatarImg: {
    width: '100%',
    height: '100%',
  },
  memberModalAvatarFallback: {
    width: '100%',
    height: '100%',
    backgroundColor: '#0C66E4',
    justifyContent: 'center',
    alignItems: 'center',
  },
  memberModalAvatarText: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: 'bold',
  },
  memberModalName: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 8,
  },
  memberModalRoleBadge: {
    backgroundColor: '#22272B',
    borderWidth: 1,
    borderColor: '#384148',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  memberModalRoleText: {
    color: '#B6C2CF',
    fontSize: 12,
    fontWeight: 'bold',
  },
});
