import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: '#22272B',
    borderRadius: 12,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#384148',
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#B6C2CF',
    marginBottom: 4,
  },
  cardSubtitle: {
    fontSize: 14,
    color: '#8C9BAB',
    marginBottom: 20,
  },
  profileHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 20,
  },
  avatarWrapper: {
    position: 'relative',
    width: 64,
    height: 64,
  },
  avatarImage: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: '#384148',
  },
  avatarPlaceholder: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#2C333A',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#384148',
  },
  avatarChangeBtn: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#2C333A',
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#384148',
  },
  userInfoCol: {
    flex: 1,
  },
  userName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  roleBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(140, 155, 171, 0.12)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginTop: 4,
    marginBottom: 4,
  },
  roleBadgeDev: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2C333A',
    borderWidth: 1,
    borderColor: '#384148',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  userRole: {
    fontSize: 10,
    color: '#8C9BAB',
    fontWeight: 'bold',
  },
  userRoleDev: {
    fontSize: 10,
    color: '#B6C2CF',
    fontWeight: 'bold',
    letterSpacing: 0.8,
  },
  userEmail: {
    fontSize: 14,
    color: '#8C9BAB',
  },
  fieldGroup: {
    marginBottom: 16,
  },
  labelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  label: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#B6C2CF',
  },
  wordCounter: {
    fontSize: 12,
    color: '#8C9BAB',
    fontWeight: '600',
  },
  wordCounterDanger: {
    color: '#EF4444',
    fontWeight: 'bold',
  },
  inputMsg: {
    backgroundColor: '#1D2125',
    borderWidth: 1,
    borderColor: '#384148',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: '#B6C2CF',
    fontSize: 14,
    minHeight: 60,
    textAlignVertical: 'top',
  },
  inputMsgError: {
    borderColor: '#EF4444',
  },
  errorText: {
    color: '#EF4444',
    fontSize: 12,
    marginTop: 4,
  },
  btnSave: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2C333A',
    borderWidth: 1,
    borderColor: '#384148',
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 4,
  },
  btnSaveText: {
    color: '#B6C2CF',
    fontSize: 14,
    fontWeight: 'bold',
  },
});
