import { StyleSheet } from 'react-native';

export const chartStyles = StyleSheet.create({
  chartContainerCard: {
    backgroundColor: '#22272B',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#384148',
    padding: 18,
    marginBottom: 20,
  },
  chartHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2C333A',
    paddingBottom: 12,
  },
  chartTitle: {
    color: '#B6C2CF',
    fontSize: 15,
    fontWeight: 'bold',
  },
  periodBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#1D2125',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#384148',
  },
  periodBadgeTxt: {
    color: '#8C9BAB',
    fontSize: 12,
    fontWeight: 'bold',
  },
  histogramWrapper: {
    height: 240,
    justifyContent: 'flex-end',
    position: 'relative',
    paddingTop: 20,
    marginBottom: 10,
  },
  gridOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'space-between',
    paddingVertical: 25,
    pointerEvents: 'none',
  },
  gridLine: {
    height: 1,
    backgroundColor: '#2C333A',
    width: '100%',
  },
  barsRowContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    flex: 1,
    minWidth: '100%',
    paddingHorizontal: 8,
    gap: 12,
  },
  columnContainer: {
    flex: 1,
    minWidth: 36,
    alignItems: 'center',
    height: '100%',
    justifyContent: 'flex-end',
  },
  barTopValue: {
    fontSize: 11,
    color: '#8C9BAB',
    fontWeight: 'bold',
    marginBottom: 6,
  },
  barTopValueActive: {
    color: '#B6C2CF',
    fontSize: 12,
    fontWeight: '900',
  },
  verticalTrack: {
    width: 28,
    height: 160,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 6,
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  verticalBarFill: {
    width: '100%',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
  },
  monthXLabel: {
    color: '#8C9BAB',
    fontSize: 11,
    fontWeight: 'bold',
    marginTop: 8,
  },
  monthXLabelActive: {
    color: '#B6C2CF',
  },
  chartFooterNotice: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#2C333A',
  },
  chartFooterTxt: {
    color: '#8C9BAB',
    fontSize: 11,
    fontStyle: 'italic',
  },
  pieContainerWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 16,
  },
  pieChartCenterWrapper: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pieCenterOverlay: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pieCenterTotalNumber: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
  },
  pieCenterTotalTxt: {
    color: '#8C9BAB',
    fontSize: 10,
    fontWeight: 'bold',
  },
  pieLegendContainer: {
    flex: 1,
    minWidth: 200,
    gap: 6,
  },
  pieLegendItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 2,
  },
  pieLegendLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    paddingRight: 6,
  },
  pieLegendColorBox: {
    width: 10,
    height: 10,
    borderRadius: 3,
  },
  pieLegendLabelTxt: {
    color: '#B6C2CF',
    fontSize: 11,
    fontWeight: '600',
    flex: 1,
  },
  pieLegendRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  pieLegendCountTxt: {
    color: '#8C9BAB',
    fontSize: 11,
    fontWeight: 'bold',
  },
  pieLegendPctTxt: {
    color: '#8C9BAB',
    fontSize: 11,
    fontWeight: 'bold',
  },
});
