import { StyleSheet } from 'react-native';

export const matrixStyles = StyleSheet.create({
  tableCard: {
    backgroundColor: '#22272B',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#384148',
    padding: 18,
  },
  tableTopHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    gap: 12,
    flexWrap: 'wrap',
  },
  tableHeaderTitleWrapper: {
    flex: 1,
    alignItems: 'flex-end',
  },
  tableTitle: {
    color: '#B6C2CF',
    fontSize: 15,
    fontWeight: 'bold',
  },
  togglePieButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#1D2125',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#384148',
  },
  togglePieButtonTxt: {
    color: '#B6C2CF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  chartSectionWrapper: {
    backgroundColor: '#1D2125',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2C333A',
    padding: 14,
    marginBottom: 16,
  },
  sectionSubtitleHeader: {
    color: '#B6C2CF',
    fontSize: 13,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  matrixContainer: {
    minWidth: 700,
    borderWidth: 1,
    borderColor: '#384148',
    borderRadius: 8,
    overflow: 'hidden',
  },
  matrixHeaderRow: {
    flexDirection: 'row',
    backgroundColor: '#1D2125',
    borderBottomWidth: 1,
    borderBottomColor: '#384148',
  },
  matrixHeaderCell: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  matrixHourHeaderCell: {
    flex: 0.8,
    minWidth: 90,
    backgroundColor: '#22272B',
  },
  matrixHeaderTxt: {
    color: '#B6C2CF',
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  matrixBodyRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#2C333A',
  },
  matrixBodyCell: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  matrixHourCell: {
    flex: 0.8,
    minWidth: 90,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(29, 33, 37, 0.5)',
  },
  matrixHourTxt: {
    color: '#8C9BAB',
    fontSize: 11,
    fontWeight: 'bold',
  },
  matrixCountBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: '#2C333A',
    minWidth: 28,
    alignItems: 'center',
  },
  matrixCountBadgeActive: {
    backgroundColor: '#384148',
  },
  matrixCountTxt: {
    color: '#8C9BAB',
    fontSize: 12,
    fontWeight: 'bold',
  },
  matrixCountTxtActive: {
    color: '#FFFFFF',
    fontWeight: '900',
  },
  matrixTotalRow: {
    flexDirection: 'row',
    backgroundColor: '#1D2125',
    borderTopWidth: 2,
    borderTopColor: '#384148',
  },
  matrixTotalTxt: {
    color: '#8C9BAB',
    fontSize: 13,
    fontWeight: '900',
  },
});
