import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  filterBarRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 12,
    marginBottom: 8,
    flexWrap: 'wrap',
  },
  btnCompararTop: {
    backgroundColor: '#1D2125',
    borderWidth: 1,
    borderColor: '#384148',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  btnCompararTopActive: {
    backgroundColor: '#2C333A',
    borderColor: '#A0B2C6',
  },
  btnCompararTopTxt: {
    color: '#8C9BAB',
    fontSize: 12,
    fontWeight: 'bold',
  },
  btnCompararTopTxtActive: {
    color: '#FFFFFF',
  },
  filterDropdownWrapper: {
    width: 240,
    marginBottom: 8,
  },
  customDateContainer: {
    backgroundColor: '#22272B',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#384148',
    padding: 10,
    marginBottom: 14,
    maxWidth: 420,
  },
  customDateTitle: {
    color: '#B6C2CF',
    fontSize: 11,
    fontWeight: 'bold',
    marginBottom: 6,
  },
  customDateRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 8,
  },
  clearDatesBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
    alignSelf: 'flex-end',
  },
  clearDatesTxt: {
    color: '#8C9BAB',
    fontSize: 11,
    fontWeight: '600',
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  loadingText: {
    color: '#8C9BAB',
    marginTop: 12,
    fontSize: 14,
  },
  soberSummaryCard: {
    backgroundColor: '#22272B',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#384148',
    paddingHorizontal: 20,
    paddingVertical: 16,
    marginBottom: 20,
    maxWidth: 580,
  },
  soberCardHeaderTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#8C9BAB',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#2C333A',
  },
  soberMetricRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#2C333A',
  },
  soberMetricInfo: {
    flex: 1,
    paddingRight: 16,
  },
  soberMetricLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#B6C2CF',
  },
  soberMetricSubtext: {
    fontSize: 12,
    color: '#8C9BAB',
    marginTop: 2,
  },
  soberMetricValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  diffBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: '#2C333A',
    marginTop: 2,
    alignSelf: 'flex-end',
    borderWidth: 1,
    borderColor: '#384148',
  },
  diffBadgeSuccess: {
    borderColor: 'rgba(56, 161, 105, 0.4)',
  },
  diffBadgeDanger: {
    borderColor: 'rgba(229, 62, 62, 0.4)',
  },
  diffBadgeTxt: {
    color: '#B6C2CF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  resultadosGridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: '#1D2125',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#384148',
    overflow: 'hidden',
    marginTop: 10,
  },
  resultadoItemCard: {
    width: '50%',
    minWidth: 240,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#2C333A',
  },
  resultadoItemCardActive: {
    backgroundColor: 'rgba(182, 194, 207, 0.05)',
  },
  resultadoItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    paddingRight: 6,
  },
  resultadoItemLabel: {
    color: '#B6C2CF',
    fontSize: 12,
    fontWeight: 'bold',
    flex: 1,
  },
  resultadoBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: '#2C333A',
    minWidth: 32,
    alignItems: 'center',
  },
  badgeSuccess: {
    backgroundColor: '#2C333A',
    borderWidth: 1,
    borderColor: 'rgba(56, 161, 105, 0.4)',
  },
  badgeDanger: {
    backgroundColor: '#2C333A',
    borderWidth: 1,
    borderColor: 'rgba(229, 62, 62, 0.4)',
  },
  resultadoBadgeTxt: {
    color: '#8C9BAB',
    fontSize: 12,
    fontWeight: 'bold',
  },
});
