import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1D2125',
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#22272B',
    borderBottomWidth: 1,
    borderBottomColor: '#384148',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#B6C2CF',
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#8C9BAB',
    marginTop: 2,
  },
  refreshIconBtn: {
    padding: 8,
    backgroundColor: '#2C333A',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#384148',
  },
  scrollContent: {
    padding: 20,
  },
  subTabRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  subTabButton: {
    flex: 1,
    minWidth: 130,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#22272B',
    borderWidth: 1,
    borderColor: '#384148',
  },
  subTabButtonActive: {
    backgroundColor: '#2C333A',
    borderColor: '#A0B2C6',
  },
  subTabText: {
    color: '#8C9BAB',
    fontWeight: 'bold',
    fontSize: 13,
  },
  subTabTextActive: {
    color: '#FFFFFF',
  },
  accessDeniedContainer: {
    flex: 1,
    backgroundColor: '#1D2125',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  accessDeniedBox: {
    backgroundColor: '#22272B',
    padding: 30,
    borderRadius: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#384148',
    maxWidth: 400,
  },
  accessDeniedTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    marginBottom: 8,
  },
  accessDeniedSubtitle: {
    color: '#8C9BAB',
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 20,
  },
  backBtn: {
    backgroundColor: '#2C333A',
    borderWidth: 1,
    borderColor: '#384148',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
  },
  backBtnText: {
    color: '#B6C2CF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  placeholderCard: {
    backgroundColor: '#22272B',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#384148',
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  placeholderTitle: {
    color: '#B6C2CF',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  placeholderSub: {
    color: '#8C9BAB',
    fontSize: 13,
    textAlign: 'center',
    maxWidth: 360,
  },
});
